modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "khimairacraft"
version = "0.1.0"
displayName = "KhimairaCraft"
authors = "DeadMind"
description = '''A D&D-inspired action-RPG for Minecraft. Class-based progression, races, feats, guilds, and an endgame Tarrasque awaits.'''

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.khimairacraft]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.khimairacraft]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"
